export enum AuditAction {
  CREATE_RECIPE = 'CREATE_RECIPE',
  UPDATE_RECIPE = 'UPDATE_RECIPE',
  DELETE_RECIPE = 'DELETE_RECIPE',

  CREATE_INGREDIENT = 'CREATE_INGREDIENT',
  UPDATE_INGREDIENT = 'UPDATE_INGREDIENT',
  DELETE_INGREDIENT = 'DELETE_INGREDIENT',
  SET_INGREDIENT = 'SET_INGREDIENT',
  SET_DEFAULT_INGREDIENT = 'SET_DEFAULT_INGREDIENT',
  ADD_INGREDIENTS = 'ADD_INGREDIENTS'
}
